/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp bodynetservice.xml -p bodynetservice-interface
 *
 * qdbusxml2cpp is Copyright (C) 2014 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef BODYNETSERVICE-INTERFACE_H_1487783870
#define BODYNETSERVICE-INTERFACE_H_1487783870

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "vitalsignsinfo.h"
#include "identificationinfo.h"

/*
 * Proxy class for interface local.BodyNetService
 */
class LocalBodyNetServiceInterface: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "local.BodyNetService"; }

public:
    LocalBodyNetServiceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~LocalBodyNetServiceInterface();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<VitalSignsInfo> GetVitalSignsInfo()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetVitalSignsInfo"), argumentList);
    }

    inline QDBusPendingReply<> SetBulletNum(int alertLevel, int totalNum, int remainNum)
    {
        QList<QVariant> argumentList;
        argumentList << QVariant::fromValue(alertLevel) << QVariant::fromValue(totalNum) << QVariant::fromValue(remainNum);
        return asyncCallWithArgumentList(QLatin1String("SetBulletNum"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void SignalBulletNum(int alertLevel, int totalNum, int remainNum);
    void SignalIdentification(IdentificationInfo info);
    void SignalShortCutKey(int keyValue);
    void SignalVitalSignsInfo(VitalSignsInfo info);
};

namespace local {
  typedef ::LocalBodyNetServiceInterface BodyNetService;
}
#endif
