#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

QT += core dbus sql network bluetooth multimedia
TARGET = phonebookservice
TEMPLATE = app

CONFIG += link_pkgconfig  c++11
PKGCONFIG += syberos-application syberos-application-cache syberos-qt-system

HEADERS += phonebookservice_workspace.h \
    groupinterface.h \
    contacterinterface.h \
    groupmessagemanager.h \
    messagemanager.h \
    receiver.h \
    sender.h \
    callhistoryinterface.h \
    sqltablemodelwithcache.h \
    chinesetopinyin.h \
    adaptor/bluetoothinterfaceadaptor.h \
    bluetoothinterface.h \
    sqlfunction.h \
    backgroundsyncinterface.h \
    ../../commondata/bluetoothdata.h \
    errorhandle.h \
    adaptor/unreadmessageadaptor.h \
    ../../commondata/bluetoothbackgroundtransferinterface.h \
    groupmessagecontroller.h \
    tcpserver/connection.h \
    tcpserver/server.h \
    tcpserver/transpondmgr.h \
    tcpserver.h \
    adaptor/downloadcontactadaptor.h \
    fileshare/fileshare.h \
    ../../commondata/callmanageradaptor/common.h \
    ../../commondata/datatype/callhistorydata.h \
    ../../commondata/datatype/commondata.h \
    ../../commondata/datatype/contacterdata.h \
    ../../commondata/datatype/groupdata.h \
    ../../commondata/datatype/messagedata.h \
    groupmessagecontroller2.h \
    ../../commondata/groupmessagetrans/CfileData.h \
    ../../commondata/groupmessagetrans/Client.h \
    ../../commondata/groupmessagetrans/MutiCast.h \
    ../../commondata/groupmessagetrans/MutiCastClient.h \
    ../../commondata/groupmessagetrans/MutiCastServer.h \
    ../../commondata/groupmessagetrans/SegData.h \
    ../../commondata/groupmessagetrans/Server.h \
    ../../commondata/groupmessagetrans/SfileData.h \
    ../../commondata/groupmessagetrans/UdpClient.h \
    ../../commondata/groupmessagetrans/UdpServer.h \
    ../../commondata/groupmessagetrans/UnCompleTab.h \
    adaptor/muticastadaptor.h \
    adaptor/fileshareadaptor.h \
    adaptor/groupshareadaptor.h \
    adaptor/contactershareadaptor.h \
    adaptor/contacterpushadaptor.h \
    ../../commondata/callmanageradaptor/DialHandler.h \
    ../../commondata/callmanageradaptor/DialManager.h \
    adaptor/groupadaptordata.h \
    adaptor/groupmessagesenderadaptor.h \
    adaptor/groupmessagesenderadaptorlte.h \
    adaptor/groupmessagesenderadaptorbt.h \
    adaptor/commondef.h \
    adaptor/pointtopointadaptor.h \
    connectiondatabase.h \
    adaptor/groupmessagesenderadaptoradhoc.h \
    downloader.h \
    adaptor/p2pvoiceadaptor.h \
    adaptor/battlecalladator.h \
    adaptor/p2ptransferadaptor.h \
    adaptor/adhocadaptor.h \
    linyun/hci_sys.h \
    linyun/hci_tts.h \
    linyun/lingyun.h \
    linyun/ttssynth.h \
    linyun/common/FileReader.h \
    adaptor/p2pmessagesendertcpadaptor.h \
    adaptor/voipserviceadaptor.h \
    adaptor/commondefadhoc.h \
    creatdatabase.h \
    audiorecorder.h
SOURCES += main.cpp \
	   phonebookservice_workspace.cpp \
    groupinterface.cpp \
    contacterinterface.cpp \
    groupmessagemanager.cpp \
    messagemanager.cpp \
    receiver.cpp \
    sender.cpp \
    callhistoryinterface.cpp \
    sqltablemodelwithcache.cpp \
    chinesetopinyin.cpp \
    adaptor/bluetoothinterfaceadaptor.cpp \
    bluetoothinterface.cpp \
    sqlfunction.cpp \
    backgroundsyncinterface.cpp \
    adaptor/unreadmessageadaptor.cpp \
    ../../commondata/bluetoothbackgroundtransferinterface.cpp \
    groupmessagecontroller.cpp \
    tcpserver/connection.cpp \
    tcpserver/server.cpp \
    tcpserver/transpondmgr.cpp \
    tcpserver.cpp \
    adaptor/downloadcontactadaptor.cpp \
    fileshare/fileshare.cpp \
    groupmessagecontroller2.cpp \
    ../../commondata/groupmessagetrans/CfileData.cpp \
    ../../commondata/groupmessagetrans/Client.cpp \
    ../../commondata/groupmessagetrans/MutiCast.cpp \
    ../../commondata/groupmessagetrans/MutiCastClient.cpp \
    ../../commondata/groupmessagetrans/MutiCastServer.cpp \
    ../../commondata/groupmessagetrans/Server.cpp \
    ../../commondata/groupmessagetrans/SfileData.cpp \
    ../../commondata/groupmessagetrans/UdpClient.cpp \
    ../../commondata/groupmessagetrans/UdpServer.cpp \
    ../../commondata/groupmessagetrans/UnCompleTab.cpp \
    adaptor/muticastadaptor.cpp \
    adaptor/fileshareadaptor.cpp \
    adaptor/groupshareadaptor.cpp \
    adaptor/contactershareadaptor.cpp \
    adaptor/contacterpushadaptor.cpp \
    ../../commondata/callmanageradaptor/DialHandler.cpp \
    ../../commondata/callmanageradaptor/DialManager.cpp \
    adaptor/groupmessagesenderadaptor.cpp \
    adaptor/groupmessagesenderadaptorlte.cpp \
    adaptor/groupmessagesenderadaptorbt.cpp \
    adaptor/pointtopointadaptor.cpp \
    connectiondatabase.cpp \
    adaptor/groupmessagesenderadaptoradhoc.cpp \
    downloader.cpp \
    adaptor/p2pvoiceadaptor.cpp \
    adaptor/battlecalladator.cpp \
    adaptor/p2ptransferadaptor.cpp \
    adaptor/adhocadaptor.cpp \
    linyun/lingyun.cpp \
    linyun/ttssynth.cpp \
    linyun/common/FileReader.cpp \
    adaptor/p2pmessagesendertcpadaptor.cpp \
    adaptor/voipserviceadaptor.cpp \
    creatdatabase.cpp \
    audiorecorder.cpp

target.path = $$INSTALL_DIR/bin

mylibs.files = libs
mylibs.path = $$INSTALL_DIR/

#lingyuns.files = lingyundata
#lingyuns.path = $$DATA_DIR/

LIBS += -L$$PWD/libs -laudio-manager -lhci_curl -lhci_sys -lhci_tts -lhci_tts_local_synth
QMAKE_RPATHDIR = $$INSTALL_DIR/libs

INSTALLS += target mylibs
#lingyuns

RESOURCES += \
    res.qrc

