#ifndef _LOCK_DEFINE_H_
#define _LOCK_DEFINE_H_

#include <pthread.h>
#include<sys/wait.h>
pthread_mutex_t mclock1;
pthread_mutex_t mclock2;
pthread_mutex_t mclock3;
pthread_mutex_t mclock4;
pthread_mutex_t mclock5;
pthread_mutex_t mclock6;
pthread_mutex_t mclock7;
pthread_mutex_t mclock8;
pthread_mutex_t mclock9;
pthread_mutex_t mclock10;
pthread_mutex_t mclock11;
pthread_mutex_t mclock12;
pthread_mutex_t mclock13;
pthread_mutex_t mclock14;
pthread_mutex_t mclock15;
pthread_mutex_t mclock16;
pthread_mutex_t mclock17;
pthread_mutex_t mclock18;
pthread_mutex_t mclock19;
pthread_mutex_t mclock20;

pthread_mutex_t m_lock1;
pthread_mutex_t m_lock2;
pthread_mutex_t m_lock3;
pthread_mutex_t m_lock4;
pthread_mutex_t m_lock5;
pthread_mutex_t m_lock6;
pthread_mutex_t m_lock7;
pthread_mutex_t m_lock8;
pthread_mutex_t m_lock9;
pthread_mutex_t m_lock10;
pthread_mutex_t m_lock11;
pthread_mutex_t m_lock12;
pthread_mutex_t m_lock13;
pthread_mutex_t m_lock14;
pthread_mutex_t m_lock15;
pthread_mutex_t m_lock16;
pthread_mutex_t m_lock17;
pthread_mutex_t m_lock18;
pthread_mutex_t m_lock19;
pthread_mutex_t m_lock20;

pthread_cond_t cond1;
pthread_cond_t cond2;
pthread_cond_t cond3;
pthread_cond_t cond4;
pthread_cond_t cond5;
pthread_cond_t cond6;
pthread_cond_t cond7;
pthread_cond_t cond8;
pthread_cond_t cond9;
pthread_cond_t cond10;
pthread_cond_t cond11;
pthread_cond_t cond12;
pthread_cond_t cond13;
pthread_cond_t cond14;
pthread_cond_t cond15;
pthread_cond_t cond16;
pthread_cond_t cond17;
pthread_cond_t cond18;
pthread_cond_t cond19;
pthread_cond_t cond20;

#endif _LOCK_DEFINE_H_
