#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

QT += gui qml quick dbus
TARGET = TerminalApp
TEMPLATE = app
DEFINES += TERMINAL

CONFIG += link_pkgconfig qml_debug
PKGCONFIG += syberos-application syberos-application-cache

RESOURCES += qml.qrc images.qrc

HEADERS += src/TerminalApp_workspace.h \
    ../../phonebook/phonebookapp/src/backgroundtransferadaptor.h \
    ../../phonebook/phonebookapp/src/bluetoothinterfaceadaptor.h \
    ../../phonebook/phonebookapp/src/callhistoryinterfaceadaptor.h \
    ../../phonebook/phonebookapp/src/contacterinterfaceadaptor.h \
    ../../phonebook/phonebookapp/src/contactershareadaptor.h \
    ../../phonebook/phonebookapp/src/downloadcontactadaptor.h \
    ../../phonebook/phonebookapp/src/fileshareadaptor.h \
    ../../phonebook/phonebookapp/src/getdata.h \
    ../../phonebook/phonebookapp/src/groupinterfaceadaptor.h \
    ../../phonebook/phonebookapp/src/messagemanageradaptor.h \
    ../../phonebook/phonebookapp/src/tablemodel.h \
    ../../phonebook/phonebookapp/src/voipdbusdata.h \
    ../../commondata/bluetoothdata.h \
    ../../commondata/datatype/callhistorydata.h \
    ../../commondata/datatype/contacterdata.h \
    ../../commondata/datatype/commondata.h \
    ../../commondata/datatype/groupdata.h \
    ../../commondata/datatype/groupips.h \
    ../../commondata/datatype/messagedata.h

SOURCES += src/main.cpp \
		   src/TerminalApp_workspace.cpp \
    ../../phonebook/phonebookapp/src/backgroundtransferadaptor.cpp \
    ../../phonebook/phonebookapp/src/bluetoothinterfaceadaptor.cpp \
    ../../phonebook/phonebookapp/src/callhistoryinterfaceadaptor.cpp \
    ../../phonebook/phonebookapp/src/contacterinterfaceadaptor.cpp \
    ../../phonebook/phonebookapp/src/contactershareadaptor.cpp \
    ../../phonebook/phonebookapp/src/downloadcontactadaptor.cpp \
    ../../phonebook/phonebookapp/src/fileshareadaptor.cpp \
    ../../phonebook/phonebookapp/src/getdata.cpp \
    ../../phonebook/phonebookapp/src/groupinterfaceadaptor.cpp \
    ../../phonebook/phonebookapp/src/messagemanageradaptor.cpp \
    ../../phonebook/phonebookapp/src/tablemodel.cpp

OTHER_FILES += qml/*.qml \
    qml/fm.js \
    qml/AddPerson.qml \
    qml/bluetooth.qml \
    qml/Call.qml \
    qml/CallRecord.qml \
    qml/CallRecordInfo.qml \
    qml/CameraRecorder.qml \
    qml/ChoicePhoto.qml \
    qml/Coming.qml \
    qml/CSwipeTab2.qml \
    qml/CSwipeTabBar2.qml \
    qml/DigitalGroup.qml \
    qml/DigitalTalk.qml \
    qml/FileChoice.qml \
    qml/FileNetwork.qml \
    qml/GroupAdd.qml \
    qml/GroupInfo.qml \
    qml/GroupMain.qml \
    qml/Groupmanagerset.qml \
    qml/GroupTitleList.qml \
    qml/mainbg.qml \
    qml/Menu.qml \
    qml/MySectionScroller.qml \
    qml/Person.qml \
    qml/PersonInfo.qml \
    qml/PersonInfoMoreInfo.qml \
    qml/PersonInfoSearch.qml \
    qml/PersonLable.qml \
    qml/PersonList.qml \
    qml/PersonSettingMemory.qml \
    qml/Photo.qml \
    qml/PhotoViewer.qml \
    qml/PictureView.qml \
    qml/PptChatRoom.qml \
    qml/SearchLine.qml \
    qml/SendFiles.qml \
    qml/Setting.qml \
    qml/TakePhoto.qml \
    qml/Message.qml

target.path = $$INSTALL_DIR/bin

res.files = res
res.path = $$INSTALL_DIR/

INSTALLS += target res

