#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

LIBS	+=	-L$$PWD/libs	-lvoicecall -lsyberos-qt
QMAKE_RPATHDIR = /usr/lib/qt5/qml/org/nemomobile/voicecall
INSTALLS	+=	voicecall

libs.files	=	libs/libvoicecall.so
libs.path	=	/usr/lib/qt5/qml/org/nemomobile/voicecall

rings.files = rings/dial.wav
rings.path = /home/user/rings/

QT += core dbus multimedia
TARGET = CallmanagerService
TEMPLATE = app

CONFIG += link_pkgconfig
PKGCONFIG += syberos-application syberos-application-cache

HEADERS += CallmanagerService_workspace.h \
    callmanager.h \
    callhandler.h \
    ../../voipService/voipcallhandler.h \
    ../../voipService/voipdbusdata.h \
    ../../voipService/voipserviceadaptor.h \
    csmanager/voicecallprovidermodel.h \
    csmanager/voicecallmodel.h \
    csmanager/voicecallmanager.h \
    csmanager/voicecallhandler.h \
    csmanager/TiantongDial.h \
    csmanager/BaotongDial.h \
    ../../voipService/sinuxvoicecallmanager.h \
    ../../voipService/voipcallmanager.h

SOURCES += main.cpp \
	   CallmanagerService_workspace.cpp \
    callmanager.cpp \
    callhandler.cpp \
    ../../voipService/voipcallhandler.cpp \
    ../../voipService/voipserviceadaptor.cpp \
    csmanager/TiantongDial.cpp \
    csmanager/BaotongDial.cpp \
    ../../voipService/sinuxvoicecallmanager.cpp \
    ../../voipService/voipcallmanager.cpp

target.path = $$INSTALL_DIR/bin

INSTALLS += target libs

RESOURCES +=

