#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

QT += core dbus sql network bluetooth
TARGET = TerminalService
TEMPLATE = app
DEFINES += TERMINAL

CONFIG += link_pkgconfig
PKGCONFIG += syberos-application syberos-application-cache syberos-qt-system

HEADERS += TerminalService_workspace.h \
    ../../phonebook/phonebookservice/backgroundsyncinterface.h \
    ../../phonebook/phonebookservice/bluetoothinterface.h \
    ../../phonebook/phonebookservice/callhistoryinterface.h \
    ../../phonebook/phonebookservice/connection.h \
    ../../phonebook/phonebookservice/chinesetopinyin.h \
    ../../phonebook/phonebookservice/contacterinterface.h \
    ../../phonebook/phonebookservice/errorhandle.h \
    ../../phonebook/phonebookservice/groupinterface.h \
    ../../phonebook/phonebookservice/groupmessagecontroller.h \
    ../../phonebook/phonebookservice/groupmessagecontroller2.h \
    ../../phonebook/phonebookservice/groupmessagemanager.h \
    ../../phonebook/phonebookservice/messagemanager.h \
    ../../phonebook/phonebookservice/receiver.h \
    ../../phonebook/phonebookservice/sender.h \
    ../../phonebook/phonebookservice/sqlfunction.h \
    ../../phonebook/phonebookservice/sqlite3.h \
    ../../phonebook/phonebookservice/sqltablemodelwithcache.h \
    ../../phonebook/phonebookservice/tcpserver.h \
    ../../phonebook/phonebookservice/tcpserver/connection.h \
    ../../phonebook/phonebookservice/tcpserver/server.h \
    ../../phonebook/phonebookservice/tcpserver/transpondmgr.h \
    ../../phonebook/phonebookservice/fileshare/fileshare.h \
    ../../phonebook/phonebookservice/adaptor/bluetoothinterfaceadaptor.h \
    ../../phonebook/phonebookservice/adaptor/contactershareadaptor.h \
    ../../phonebook/phonebookservice/adaptor/downloadcontactadaptor.h \
    ../../phonebook/phonebookservice/adaptor/fileshareadaptor.h \
    ../../phonebook/phonebookservice/adaptor/groupshareadaptor.h \
    ../../phonebook/phonebookservice/adaptor/muticastadaptor.h \
    ../../phonebook/phonebookservice/adaptor/unreadmessageadaptor.h \
    ../../commondata/callmanageradaptor/DialHandler.h \
    ../../commondata/callmanageradaptor/DialManager.h \
    ../../commondata/datatype/commondata.h \
    ../../commondata/datatype/contacterdata.h \
    ../../commondata/datatype/dialdata.h \
    ../../commondata/datatype/groupdata.h \
    ../../commondata/datatype/groupips.h \
    ../../commondata/datatype/messagedata.h \
    ../../commondata/datatype/callhistorydata.h \
    ../../commondata/bluetoothbackgroundtransferinterface.h \
    ../../commondata/bluetoothdata.h \
    ../../phonebook/phonebookservice/adaptor/contacterpushadaptor.h

SOURCES += main.cpp \
	   TerminalService_workspace.cpp \
    ../../phonebook/phonebookservice/backgroundsyncinterface.cpp \
    ../../phonebook/phonebookservice/bluetoothinterface.cpp \
    ../../phonebook/phonebookservice/callhistoryinterface.cpp \
    ../../phonebook/phonebookservice/chinesetopinyin.cpp \
    ../../phonebook/phonebookservice/contacterinterface.cpp \
    ../../phonebook/phonebookservice/groupinterface.cpp \
    ../../phonebook/phonebookservice/groupmessagecontroller.cpp \
    ../../phonebook/phonebookservice/groupmessagecontroller2.cpp \
    ../../phonebook/phonebookservice/groupmessagemanager.cpp \
    ../../phonebook/phonebookservice/messagemanager.cpp \
    ../../phonebook/phonebookservice/receiver.cpp \
    ../../phonebook/phonebookservice/sender.cpp \
    ../../phonebook/phonebookservice/sqlfunction.cpp \
    ../../phonebook/phonebookservice/sqltablemodelwithcache.cpp \
    ../../phonebook/phonebookservice/tcpserver.cpp \
    ../../phonebook/phonebookservice/tcpserver/connection.cpp \
    ../../phonebook/phonebookservice/tcpserver/server.cpp \
    ../../phonebook/phonebookservice/tcpserver/transpondmgr.cpp \
    ../../phonebook/phonebookservice/fileshare/fileshare.cpp \
    ../../phonebook/phonebookservice/adaptor/bluetoothinterfaceadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/contactershareadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/downloadcontactadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/fileshareadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/groupshareadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/muticastadaptor.cpp \
    ../../phonebook/phonebookservice/adaptor/unreadmessageadaptor.cpp \
    ../../commondata/callmanageradaptor/DialHandler.cpp \
    ../../commondata/callmanageradaptor/DialManager.cpp \
    ../../commondata/bluetoothbackgroundtransferinterface.cpp \
    ../../phonebook/phonebookservice/adaptor/contacterpushadaptor.cpp

target.path = $$INSTALL_DIR/bin

INSTALLS += target

OTHER_FILES += \
    ../../phonebook/phonebookservice/pinyingbknotongyin \
    ../../phonebook/phonebookservice/pinyingbktongyin

