#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

QT += gui qml quick dbus
TARGET = TerminalcallApp
TEMPLATE = app
DEFINES += TERMINAL

CONFIG += link_pkgconfig qml_debug
PKGCONFIG += syberos-application syberos-application-cache
PKGCONFIG += syberos-qt-system

RESOURCES += qml.qrc images.qrc

HEADERS += src/TerminalcallApp_workspace.h \
    ../../PhoneCall/MyApp/src/callhistoryinterfaceadaptor.h \
    ../../PhoneCall/MyApp/src/contacterinterfaceadaptor.h \
    ../../PhoneCall/MyApp/src/dialinterfaceadaptor.h \
    ../../PhoneCall/MyApp/src/screenshot.h \
    ../../PhoneCall/MyApp/src/SharedMemory.h \
    ../../PhoneCall/MyApp/src/tablemodel.h \
    ../../commondata/datatype/callhistorydata.h \
    ../../commondata/datatype/commondata.h \
    ../../commondata/datatype/contacterdata.h \
    ../../commondata/datatype/dialdata.h

SOURCES += src/main.cpp \
		   src/TerminalcallApp_workspace.cpp \
    ../../PhoneCall/MyApp/src/callhistoryinterfaceadaptor.cpp \
    ../../PhoneCall/MyApp/src/contacterinterfaceadaptor.cpp \
    ../../PhoneCall/MyApp/src/dialinterfaceadaptor.cpp \
    ../../PhoneCall/MyApp/src/screenshot.cpp \
    ../../PhoneCall/MyApp/src/SharedMemory.cpp \
    ../../PhoneCall/MyApp/src/tablemodel.cpp

OTHER_FILES += qml/*.qml

target.path = $$INSTALL_DIR/bin

res.files = res
res.path = $$INSTALL_DIR/

INSTALLS += target res

