#-------------------------------------------------
#
# Project generated by QtCreator for SyberOS.
#
#-------------------------------------------------

# This is needed for using syberos-application module
include(../syberos.pri)

QT += core dbus sql network
TARGET = DownloaderContactInterfaceModuleService
TEMPLATE = app

CONFIG += link_pkgconfig c++11
PKGCONFIG += syberos-application syberos-application-cache

INCLUDEPATH += /home/michael/SyberOS-SDK2/jail/opt/cross/armv7tnhl-meego-linux-gnueabi/sys-root/usr/include
LIBS += -lz -lrt
HEADERS += DownloaderContactInterfaceModuleService_workspace.h \
    interface/downloadcontactinterface.h \
    datatype/serverdata.h \
    datatype/groupdata.h \
    datatype/contacterdata.h \
    downloadcontact.h \
    request2.h \
    datatype/commondata.h

SOURCES += main.cpp \
	   DownloaderContactInterfaceModuleService_workspace.cpp \
    interface/downloadcontactinterface.cpp \
    downloadcontact.cpp \
    request2.cpp

target.path = $$INSTALL_DIR/bin

INSTALLS += target

OTHER_FILES += \
    ../sopconfig.xml
